// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBioSlqXIvXhqTzwppw5mLRSKp4CJwJlio',
    appId: '1:607529736390:web:56badd7151a18f397f1fc7',
    messagingSenderId: '607529736390',
    projectId: 'anbar-7232b',
    authDomain: 'anbar-7232b.firebaseapp.com',
    storageBucket: 'anbar-7232b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuvE25PBxH9gz43v9Wy5UmQijk_mNu3pg',
    appId: '1:607529736390:android:99ec1ddf17b62ad37f1fc7',
    messagingSenderId: '607529736390',
    projectId: 'anbar-7232b',
    storageBucket: 'anbar-7232b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdrXF3jfRePVu0os-l_jV7g7nOQchy7es',
    appId: '1:607529736390:ios:ada624308b6fbd387f1fc7',
    messagingSenderId: '607529736390',
    projectId: 'anbar-7232b',
    storageBucket: 'anbar-7232b.appspot.com',
    iosBundleId: 'com.example.anbar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdrXF3jfRePVu0os-l_jV7g7nOQchy7es',
    appId: '1:607529736390:ios:ada624308b6fbd387f1fc7',
    messagingSenderId: '607529736390',
    projectId: 'anbar-7232b',
    storageBucket: 'anbar-7232b.appspot.com',
    iosBundleId: 'com.example.anbar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBioSlqXIvXhqTzwppw5mLRSKp4CJwJlio',
    appId: '1:607529736390:web:f3aea95f53ec7c097f1fc7',
    messagingSenderId: '607529736390',
    projectId: 'anbar-7232b',
    authDomain: 'anbar-7232b.firebaseapp.com',
    storageBucket: 'anbar-7232b.appspot.com',
  );

}